version: "3.8"

services:
  ExpressApi:
    container_name: ExpressApi
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
        context: ./
    ports:
      - 8080:8080
